"""
add healthcare facilities

Revision ID: 1080ccb9f184
Revises: 9e95541c5d42
Create Date: 2026-07-03 13:19:16.456836
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1080ccb9f184"
down_revision: str | None = "9e95541c5d42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "healthcare_facilities",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("name_hi", sa.String(length=500), nullable=True),
        sa.Column("facility_type", sa.String(length=100), nullable=False),
        sa.Column("district", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("specialties", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("total_beds", sa.Integer(), nullable=False),
        sa.Column("available_beds", sa.Integer(), nullable=False),
        sa.Column("is_accepting_patients", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_healthcare_facilities_district"),
        "healthcare_facilities",
        ["district"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_healthcare_facilities_district"), table_name="healthcare_facilities")
    op.drop_table("healthcare_facilities")
    # ### end Alembic commands ###
