"""
Add DataSyncLog and sync fields

Revision ID: 3fa1e3112e01
Revises: 87deb437b00b
Create Date: 2026-07-04 01:02:50.740614
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fa1e3112e01"
down_revision: str | None = "87deb437b00b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sync_logs",
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("records_synced", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_sync_logs_source_name"), "data_sync_logs", ["source_name"], unique=False
    )
    op.create_index(op.f("ix_data_sync_logs_status"), "data_sync_logs", ["status"], unique=False)
    op.add_column("healthcare_facilities", sa.Column("hfr_id", sa.String(), nullable=True))
    op.add_column("healthcare_facilities", sa.Column("source_api", sa.String(), nullable=True))
    op.add_column(
        "healthcare_facilities", sa.Column("last_synced_at", sa.DateTime(), nullable=True)
    )
    op.create_unique_constraint(None, "healthcare_facilities", ["hfr_id"])
    op.add_column("mandi_prices", sa.Column("source_api", sa.String(length=255), nullable=True))
    op.add_column("mandi_prices", sa.Column("last_synced_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mandi_prices", "last_synced_at")
    op.drop_column("mandi_prices", "source_api")
    op.drop_constraint(None, "healthcare_facilities", type_="unique")
    op.drop_column("healthcare_facilities", "last_synced_at")
    op.drop_column("healthcare_facilities", "source_api")
    op.drop_column("healthcare_facilities", "hfr_id")
    op.drop_index(op.f("ix_data_sync_logs_status"), table_name="data_sync_logs")
    op.drop_index(op.f("ix_data_sync_logs_source_name"), table_name="data_sync_logs")
    op.drop_table("data_sync_logs")
    # ### end Alembic commands ###
