"""
add mandi prices

Revision ID: 7b30d848d3e3
Revises: 1080ccb9f184
Create Date: 2026-07-03 15:17:13.921376
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b30d848d3e3"
down_revision: str | None = "1080ccb9f184"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mandi_prices",
        sa.Column("crop_name", sa.String(length=255), nullable=False),
        sa.Column("crop_name_hi", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("district", sa.String(length=255), nullable=False),
        sa.Column("market_name", sa.String(length=255), nullable=False),
        sa.Column("min_price", sa.Float(), nullable=False),
        sa.Column("max_price", sa.Float(), nullable=False),
        sa.Column("modal_price", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mandi_prices_crop_name"), "mandi_prices", ["crop_name"], unique=False)
    op.create_index(op.f("ix_mandi_prices_district"), "mandi_prices", ["district"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mandi_prices_district"), table_name="mandi_prices")
    op.drop_index(op.f("ix_mandi_prices_crop_name"), table_name="mandi_prices")
    op.drop_table("mandi_prices")
    # ### end Alembic commands ###
