"""
Add onboarding_complete to user

Revision ID: 7fe5b7385227
Revises: 07d7ff2ac3cf
Create Date: 2026-07-04 00:33:12.873201
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe5b7385227"
down_revision: str | None = "07d7ff2ac3cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("onboarding_complete", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarding_complete")
    # ### end Alembic commands ###
