"""
Add organization_id to AnonymousReport

Revision ID: 87deb437b00b
Revises: 2e8c04a22f68
Create Date: 2026-07-04 00:41:18.122130
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87deb437b00b'
down_revision: Union[str, None] = '2e8c04a22f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_reports', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_anonymous_reports_organization_id'), 'anonymous_reports', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'anonymous_reports', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anonymous_reports', type_='foreignkey')
    op.drop_index(op.f('ix_anonymous_reports_organization_id'), table_name='anonymous_reports')
    op.drop_column('anonymous_reports', 'organization_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
