"""
add authorities and anonymous_reports tables

Revision ID: 9e95541c5d42
Revises: 93896ec8a2d6
Create Date: 2026-07-03 12:46:59.610627
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e95541c5d42"
down_revision: str | None = "93896ec8a2d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_reports",
        sa.Column("report_token", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("content_encrypted", sa.Text(), nullable=False),
        sa.Column("district", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("target_authority_title", sa.String(length=255), nullable=True),
        sa.Column("routed_to_level", sa.Integer(), nullable=False),
        sa.Column("routed_to_department", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anonymous_reports_report_token"),
        "anonymous_reports",
        ["report_token"],
        unique=True,
    )
    op.create_table(
        "authorities",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("title_hi", sa.String(length=255), nullable=True),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("district", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("reports_to_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reports_to_id"],
            ["authorities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authorities")
    op.drop_index(op.f("ix_anonymous_reports_report_token"), table_name="anonymous_reports")
    op.drop_table("anonymous_reports")
    # ### end Alembic commands ###
