"""
add notifications_enabled to users

Revision ID: e3198948670c
Revises: 7b30d848d3e3
Create Date: 2026-07-03 22:52:13.492234
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3198948670c'
down_revision: Union[str, None] = '7b30d848d3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    # ### end Alembic commands ###
